import type { Metadata } from 'next';

import './globals.css';
import { inter, neueHaasDisplay } from '@/fonts';
import type { LayoutComponent } from '@/serverComponent';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: LayoutComponent = ({ children }) => {
  return (
    <html lang="en" className={`${inter.variable} ${neueHaasDisplay.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
};

export default RootLayout;
